name: HTML Preview

on: [push]

jobs:
  html-preview

  steps:
    -name: html_preview
    uses: pavi2410/html-preview-action@v2
    with:
      # The HTML file you want to preview, relative to the root of the repo
      html_file: src/index.html
